
# Puerto del servidor de Service Discovery
server.port=8761
spring.application.name=ms-eureka

# El servidor Eureka NO se registra a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Desactivar auto-preservacion
eureka.server.enable-self-preservation=false

management.endpoints.web.exposure.include=health,info
